# Generated by Django 6.0 on 2025-12-19 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='title_ref',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='position_modules', to='learning.moduletitle'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('title_ref', 'position')},
        ),
        migrations.RemoveField(
            model_name='module',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='module',
            name='title',
        ),
    ]
