# Generated by Django 6.0 on 2025-12-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_finalquizprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
    ]
