# Generated by Django 6.0 on 2025-12-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_alter_module_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepage',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulepage',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
